#!/bin/bash

if [[ $# -ne 1 ]] ; then
    echo 'usage: tools/create-patch-branch <branchname>'
    echo
    echo 'examples: tools/create-patch-branch fancypatch'
    echo '          tools/create-patch-branch "my fancy patch"'
    exit 1
fi

echo "Switching to patch"
git checkout master

echo "Updating master"
git pull --all --prune --progress

echo "Rebasing master"
#git rebase upstream/master master
git reset --hard upstream/master

if [ $? != 0 ]; then
    echo "Can't rebase to master. Unstaged changes?"
    exit 1
fi

echo "Creating patch branch"
git checkout -b patch-${1//[^a-zA-Z0-9]/_} master

echo "Done"
