#!/bin/bash

yum install -y httpd.x86_64 conda gridsite mod_ssl.x86_64
mkdir /opt/idds
mkdir /opt/idds_source
# git clone @github_idds@ /opt/idds_source
# python setup.py install --old-and-unmanageable

conda env create --prefix=/opt/idds -f idds_source/tools/environment.yml
conda activate /opt/idds
pip install mod_wsgi
#conda deactivate

